#! /bin/bash

path="`pwd`"
cd $1

wget2 -c "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_0.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_1.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_2.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_3.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_4.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_5.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_6.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_7.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_8.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_9.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_10.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_11.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_12.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_13.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_14.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_15.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_16.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_17.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_18.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/train_19.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/val.zip" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/fg_bg_ratios_train.json" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/fg_bg_ratios_val.json" "https://huggingface.co/datasets/TNauen/ForNet/resolve/main/settings.txt"

touch .dl_done

cd $path